### ISSUE TITLE
Option to include additional logo on frontpage

### ISSUE THREAD

**Issue by tjuberg** [COPCSE-NTNU/bachelor-thesis-NTNU#10]
For bachelor assignments carried out for external organizations or companies, it would be nice to have an option in the template to include their logo on the frontpage.

**Comment by ifarup** [comment]
According to NTNU's regulations, we have to use a standardized frontpage:

https://innsida.ntnu.no/wiki/-/wiki/Norsk/ferdigstille+bachelor-+og+masteroppgave

Future versions of the template will only provide a dummy frontpage that will be substituted with the official one upon hand-in.
