### ISSUE TITLE
Changes to bachelor programs

### ISSUE THREAD

**Issue by Celebrian** [COPCSE-NTNU/bachelor-thesis-NTNU#17]
Bachelor i drift av nettverk og datasystemer and Bachelor i Informasjonssikkerhet have been combined into Bachelor i IT-Drift og informasjonssikkerhet. I'm not sure myself how to edit this template to use this for out bachelor report.  The merging of these two into BITSEC would be nice
Assistance would be greatly appreciated.

**Comment by SimonMcCallum** [comment]
I have left the old options there as some students might still be finishing the old degrees.
