### ISSUE TITLE
Glossary 

### ISSUE THREAD

**Issue by SimonMcCallum** [COPCSE-NTNU/bachelor-thesis-NTNU#24]
The issue is, we wish to use a glossary to define necessary, not self-explainable words.

Where and how would this be added in the template?

**Comment by ifarup** [comment]
I propose to simply put the following after \listoflistings (or as an appendix)

\chapter*{Glossary}

\begin{description}
\item[Word one] Description one
\item[Word two] Description two
...
\end{description}

**Comment by ifarup** [comment]
Proposed solution worked well for several groups.
