### ISSUE TITLE
Creat a printable book cover

### ISSUE THREAD

**Issue by SimonMcCallum** [COPCSE-NTNU/bachelor-thesis-NTNU#7]
The new NTNU templates include a bachelor thesis cover design for book publishing [innsida bachelor template](https://innsida.ntnu.no/wiki/-/wiki/Norsk/Ferdige+maler+for+trykksaker#Bacheloroppgave)

**Comment by marni** [comment]
I'm currently closing it, as it seems all the book covers are done independent of the actual PDF rendering of the final thesis. If need be, we can re-open the issue.
