### ISSUE TITLE
Option to include bachelor assignment code on frontpage/summary

### ISSUE THREAD

**Issue by tjuberg** [COPCSE-NTNU/bachelor-thesis-NTNU#9]
At least some bachelors need to include the bachelor assignment code in one of, or both front page and summary.

Would be nice if this was supported in the template directly.

**Comment by SimonMcCallum** [comment]
By bachelor assignment code I assume you mean the IMT3912 for example

**Comment by tjuberg** [comment]
In retrospect this was unclear.

As an example
http://www.iie.ntnu.no/prosjekter/hovedprosjekt/v2017/29e/29e.html

Our bachelor assignment code/number is 29E for example. There is no requirement for us to include the course code, i.e. IDRI3001 in our case.

**Comment by SimonMcCallum** [comment]
Indeed the course code is not needed
